prima: vos_api: Fix definition of vos_process_bt_profile
* Fixes build error introduced in commit: 1982ed4d9cc3f6b3e026806d20fa419440339835

"wlan: Add support to send BT advertisement via bt_profile"

drivers/staging/prima/CORE/VOSS/inc/vos_api.h:627:1: error: expected identifier or '('
{
^