prima: Fix strict prototype warnings
Caused by:

error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]

Signed-off-by: Aditya Eka Pranata <aepranata@gmail.com>